I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/minigame.rpy", line 256, in script
    with pause(2.0)
  File "game/minigame.rpy", line 256, in <module>
    with pause(2.0)
NameError: name 'pause' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/minigame.rpy", line 256, in script
    with pause(2.0)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\ast.py", line 1356, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/minigame.rpy", line 256, in <module>
    with pause(2.0)
NameError: name 'pause' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
FishLoveMe 1.0
Sun May  5 15:51:53 2024
